# localhost:1313 for local development, gets overwritten in deployment
baseURL = "http://localhost:1313/"
locale = 'us-en'
title = 'SUPC'
theme = 'ananke'

[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[params]
facebook_url = "https://www.facebook.com/supcreading/"